spring:
  application:
    name: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/Marketplace
    username: postgres
    password: brb123/xd/brb431
  jpa:
    generate-ddl: false
    show-sql: false
  jjwt:
    duration: 300000
    secret: 3a0d6741-5156-4711-8c40-dc7537b0f85e